### ISSUE TITLE
Setup parallel production and development resources on Azure

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/CROP#197]
We currently have resource groups called `cropapp` and `cropapptest`, where `cropapptest` is the de facto production version.

The state we want to end up in is that we have database, function apps, webapp, replicated in both, with `cropapp` being the production one (docker containers being built by Travis upon pushes to `main`), and `cropapptest` being the development one (docker containers being built by Travis upon pushes to `develop`.

To do this:
 - [x] Pull function app docker container, check that code is same. as currently in repo - turns out there is more code in Github than in docker container, but we will go ahead and make new Docker image from what is in `main`, then compare results with what is in `cropapptest` after a few days.
 - [x] Build a function app container locally, using code in `main`, and push to a new container name "functions", with tag `prod`
 - [x] Make new function apps in Azure from that container, in resource group `cropapp`. See that they run, except they should point to a non-existent database
 - [x] Make Travis build the function app container automatically
 - [x] Make the database/repurpose the old one to be the `prod` version.
 - [x] Dump/restore data from the dev database to the new prod one
 - [x] Make webapp in `cropapp` resource group (replacing deployment slots one).
 - [x] Make prod website point to prod database.
 - [ ] Make a `prod` version of the modelling runs, have them populate the `prod` database with predictions.
 - [ ] After verifying that we get the same data, including updates at expected times, in `cropapp` webapp as in `cropapptest` webapp, inform everyone that the `cropapp` one is now the stable production one, and `cropapptest` will become the test one.
 - [ ] Switch `cropapptest` webapp and function app to use docker containers built by Travis upon pushes to `develop`.

**Comment by mhauru** [comment]
So that I don't forget: The two databases produce very similar looking plots now and the function app is pulling more data into the prod db as it should. But I did spot some small discrepancies between the dbs, e.g. the zensie_trh_data table is missing a uniqueness constraint on timestamps and has more rows than the cropapptest one (sounds like duplicate rows).

**Comment by mhauru** [comment]
The GES model has now been running on an Azure function since yesterday, twice a day. This means that there are, as far as I can see, three things left before we can declare feature parity between `dev` and `prod`:
1) The Arima model (written in R) should also be moved to Azure. This could be trickier because R isn't officially supported for function apps, but not impossible, there are workarounds. Rebecca was also considering at some point migrating the Arima model to Python.
2) There are still some tiny discrepancies between the data in the two databases, I think around the time when I did the dump/restore. Not sure what's causing them, need to investigate. You can see them in the stratification plots on the front page, if you alt+tab between cropapp and cropapptest and look at the point at e.g. 2022-05-08T09.
3) I'm currently running the GES model on Azure with far fewer points used in calibration, because it's so slow that even now it's taking more than half an hour, and the maximum time out at the tier I'm using (Premium) is an hour. This means that the predictions are pretty bad, and can't be compared to the `dev` ones, which use more calibration points. Unsure as to what the best way forward here is. Rebecca wants to change the way the function is run, so that it's done more frequently but requires much less time each time. That sounds great, but if we go straight to that then we'll miss checking the feature parity.
