### ISSUE TITLE
Ideas for visualization and analysis of crop data

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/CROP#348]
Placeholder issue.   Feel free to link to separate Issues for specific ideas, or add them as comments to this one.

We will discuss and work on these ideas and more at the workshop on Friday 21st Oct 2022.

**Comment by nbarlowATI** [comment]
**One idea:   T/RH/VPD time series grouped by crop type**
Building off what is already there in the "Crop"/"View" page per batch, we could have, for each crop type (e.g. "Peashoots"), a set of time series plots (one plot for each of T, RH, VPD).   On each plot we would have one line per harvested batch, all aligned with the harvest time on the rhs of the plot.   The lines would be coloured and/or weighted, by yield-per-area (and mouse-over would also display yield and loss information).
![Screenshot 2022-10-05 at 15 26 06](https://user-images.githubusercontent.com/33832774/194085519-422f4bda-f429-498a-a98c-62f0a5645d11.png)

**Comment by dsj976** [comment]
The idea I mentioned in Tuesday's meeting is to apply the concept of [Multivariate Statistical Process Control](https://www.sciencedirect.com/science/article/pii/S1474667017482036), typically used to monitor chemical processes (where many variables are measured over time). Essentially, if you have historical data from a *normal chemical process*, you can use it to build a PCA model. Then, live-stream chemical process data can be projected onto this model, and if the projection of a particular multivariate time-point is "not good" (i.e. if it's an outlier observation), a warning is displayed as it is an indicator that something is going wrong in the chemical process being monitored.
Not sure how applicable this idea is to CROP, but it might be worthwhile investigating - it could be useful to identify a situation in which something is happening that doesn't normally happen, which would be hard to identify by looking at each individual time series separately.

**Comment by zackxconti** [comment]
One potential approach to visualise crop harvest data is using _parallel coordinate plots_. 

A parallel coordinate plot (aka parallel plot) is composed of vertical axes, each representing variables from the csv dataset. It is typical to position your dependant variable or measured variable as your last variable to the right to assist better legibility. Typically, parallel plots are used to display continous variables however some python plotting packages offer customisation for categorical variables. Parallel plots are popular because they offer an intuitive snapshot of the correlations between variables by visually observing how the 'data lines' bundle up between variables. Note that, these intuitive properties may be compromised when adapting the plot for categorical variables. 

Here are a few attempts of visualising crop harvest data using parralel plots, while varying what the colors represent:

Color by crop type:

![image](https://user-images.githubusercontent.com/23521079/195144038-628b7567-90b5-4f22-87c2-618ed6a2af80.png)

Color by crop yield: 

![image](https://user-images.githubusercontent.com/23521079/195143763-297157c4-3636-4d72-8e54-e2bfccf8deb2.png)
