### ISSUE TITLE
Add all possible farm locations

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/CROP#404]
We currently add locations to the DB as needed. 
However, for the 3D model, we want to have some info (e.g. nearest sensor/reading) for every shelf, so it would make sense to add any possible location in the farm (i.e. with a valid aisle/column/shelf) to the DB.

**Comment by mhauru** [comment]
Yeah, I think this is overdue, we've been talking about this since the summer. I feel like the Right solution might be to get rid of the locations table, or in some other way change how the set of valid locations is defined, but I'm also inclined to say that implementing such a thing now wouldn't be the best use of our time.
